FROM registry.access.redhat.com/ubi8/ubi:override-me-as-buid-arg

ARG SPARK_VERSION=3.3.0
ARG HADOOP_VERSION=3

USER root

# Spark
ADD https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz /root
