#!/bin/sh

SCRIPT_DIR=$(dirname $0)
ARTIFACTS_DIR=/tmp/artifacts
fullname=$(find $ARTIFACTS_DIR -name spark-[0-9.]*\.tgz)

# Make a place for spark to go
if ! [ -d $SPARK_INSTALL ]; then
    mkdir -p $SPARK_INSTALL/conf
    ln -sfn $SPARK_INSTALL/distro $SPARK_HOME
fi

pushd $SPARK_INSTALL
cp $fullname .
tar -zxf $(basename $fullname)
ln -s $(basename $fullname .tgz) distro
rm $(basename $fullname)
popd

# Make everything under the spark directory accessible to the group
chown 185:0 $SPARK_INSTALL/distro && chmod g+rwX $SPARK_INSTALL/distro

# Search for the spark entrypoint file and copy it to $SPARK_INSTALL
entry=$(find $SPARK_HOME/kubernetes -name entrypoint.sh)
if [ -n "$entry" ]; then
    cp $entry $SPARK_INSTALL

    # We want to get rid of the tini invocation
    sed -i "s@exec .*/tini -s --@exec@" $SPARK_INSTALL/entrypoint.sh
fi
