apiVersion: batch/v1
kind: Job
metadata:
  name: minio-configure
  labels:
    app.kubernetes.io/name: minio
spec:
  template:
    metadata:
      name: minio-setup
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: config
          emptyDir: {}
        - configMap:
            defaultMode: 420
            name: modelconfig
          name: modelconfig
        - configMap:
            defaultMode: 420
            name: promconfig
          name: promconfig
      containers:
        - name: mc
          image: minio/mc:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "echo add mc commands here"
#            - "mc --config-dir=/config config host add local http://minio:9000 minio minio123 && mc --config-dir=/config mb --ignore-existing local/data/ && mc --config-dir=/config policy set public local/data"
          volumeMounts:
            - name: config
              mountPath: "/config"
            - mountPath: /tmp/models.config
              name: modelconfig
              subPath: models.config
            - mountPath: /tmp/prometheus_config.config
              name: promconfig
              subPath: prometheus_config.config
